### ISSUE TITLE
Key is truncated in ParseLine()

### ISSUE THREAD

**Issue by rayz55** [Lek-sys/LeksysINI#1]
I compiled in Visual Studio 17 using ASCII character encoding. All of the keys in my ini file had the last character removed i.e. "dENCODER_CNT_PER_UNIT" was truncated to "dENCODER_CNT_PER_UNI". The section names and values were OK.
I fixed the issue by changing line 1278 from:
    key = input_line.substr(0,pos-1);
to:
    key = input_line.substr(0,pos);

**Comment by Lek-sys** [comment]
Thx, that was a mistake. 
Always passed through my tests, since I never used 'key=val' (without space between key and '=' sign) syntax. 
Fixed.
